convert proxy to optional dep; allow direct connection to bitcoind
Start9Labs/c-lightning-wrapper pull request #35
Opened 2022-03-22 22:17 UTC by chrisguida

Fixes #17

2022-03-23 16:44 UTC, elvece commented on check-synced.sh
> +# if ! [ -s /root/.lightning/config ]; then
delete or uncomment

2022-03-23 16:46 UTC, elvece commented on manifest.yaml
> +      how: Can alternatively configure an internal Bitcoin Proxy, or an external bitcoin node.
```suggestion
      how: Can alternatively configure the internal Bitcoin Proxy service, or an external bitcoin node.
```

2022-03-23 16:49 UTC, elvece commented
In order for proxy/bitcoin to display in the UI as a required dependency *if* selected in the config, you will need to add the [dependencies rules file](https://github.com/Start9Labs/btcpayserver-wrapper/blob/b8096529b0ed3230e881590cf73581fb17b3570d/assets/compat/dependencies.yaml). Then, call this file in the config.set action, [like so](https://github.com/Start9Labs/btcpayserver-wrapper/blob/b8096529b0ed3230e881590cf73581fb17b3570d/manifest.yaml#L90).

2022-03-23 16:50 UTC, elvece requested changes
In order for proxy/bitcoin to display in the UI as a required dependency *if* selected in the config, you will need to add the [dependencies rules file](https://github.com/Start9Labs/btcpayserver-wrapper/blob/b8096529b0ed3230e881590cf73581fb17b3570d/assets/compat/dependencies.yaml#L9-L11). Then, call this file in the config.set action, [like so](https://github.com/Start9Labs/btcpayserver-wrapper/blob/b8096529b0ed3230e881590cf73581fb17b3570d/manifest.yaml#L90).

2022-03-24 14:32 UTC, chrisguida commented
@elvece my understanding is that dependencies.yaml is not necessary if there's a pointer to bitcoind

2022-03-28 22:54 UTC, ProofOfKeags commented
No additional comments beyond what @elvece pointed out.

2022-03-29 16:58 UTC, chrisguida commented on manifest.yaml
> +      how: Can alternatively configure an internal Bitcoin Proxy, or an external bitcoin node.
Done

2022-03-29 16:58 UTC, chrisguida commented on check-synced.sh
> +# if ! [ -s /root/.lightning/config ]; then
Done

2022-03-29 16:58 UTC, merged